### ISSUE TITLE
What are the storage format requirements for importing yjs documents

### ISSUE THREAD

**Issue by HengCC** [yjs/yjs-playground#5]
This project is very interesting. I saw it in another issue. I want to ask if you import yjs files. Any formatting requirements? I am currently persisting the binary string form of doc, and when I try to import, I am prompted to import failure.

**Comment by lawvs** [comment]
Very happy that you are interested in this project, currently yjs- playground uses `Y.applyUpdate` to parse yjs files, you can use `Y.encodeStateAsUpdate(yDoc)` to get the corresponding binary content.

Certainly! I plan to support additional formats, including base64 encoding for binary data. Could you specify the format you are currently using? I am eager to expand support for a wider range of formats.


You can also find more details in the following code.

https://github.com/yjs/yjs-playground/blob/22293fac3bd3e53de5c4922afc1cf9181b31797c/src/utils.ts#L4-L13

**Comment by HengCC** [comment]
Thanks for your reply, I used the tostring method to convert to binary string.
```js
store: async (payload) => {
        const { documentName, state, context } = payload;
        const fileResource = {
          id: documentName,
          content: state.toString("binary")
        };
```
the `content` above is the final stored string content.

**Comment by lawvs** [comment]
Can you explain `state.toString("binary")`? It seems that there is no such function in Yjs.

**Comment by HengCC** [comment]
state is a Buffer object in Nodejs, and I use its toString api.Reference link below: 
`https://nodejs.org/api/buffer.html#buftostringencoding-start-end`
 and  the following api is used to restore buffer objects
`Buffer.from(content, 'binary')`

`content` is the `state.toString("binary") `mentioned above.

**Comment by lawvs** [comment]
I have added parsing support for the binary string, thank you for your feedback. If it's still not working, feel free to reopen this issue.

Closed in https://github.com/yjs/yjs-playground/commit/1547092d27f91bf04050639b96aad21ddd9b8604
